name: Shared Maven & Docker CI/CD

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: '21'
      needs-mysql:
        type: boolean
        default: false
      needs-redis:
        type: boolean
        default: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # Required to upload JARs to GitHub Packages

    # Services defined at the JOB level (not inside steps)
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          server-id: github # Injects GitHub credentials into ~/.m2/settings.xml
          cache: 'maven'

      - name: Build and Publish to GitHub Packages
        run: mvn clean deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: vamshivoore
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
             vamshivoore/${{ github.event.repository.name }}:latest
#            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}
